#define _POSIX_C_SOURCE 200809L

#include "dhcp_sv.h"
#include "log.h"

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <errno.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>

/* LAN DHCP server: wraps dnsmasq. Config at STATE_DIR/dnsmasq.conf. */

#define DNSMASQ_CONF  "/var/lib/route-daemon/dnsmasq.conf"

static pid_t child_pid = -1;

static int ensure_state_dir(void) {
    if (mkdir("/var/lib/route-daemon", 0755) < 0 && errno != EEXIST) {
        log_error("dhcp_server: mkdir /var/lib/route-daemon: %s", strerror(errno));
        return -1;
    }
    return 0;
}

static int write_config(const rd_config *cfg) {
    FILE *f = fopen(DNSMASQ_CONF, "w");
    if (f == NULL) {
        log_error("dhcp_server: fopen %s: %s", DNSMASQ_CONF, strerror(errno));
        return -1;
    }
    fprintf(f,
        "# Generated by route-daemon\n"
        "interface=%s\n"
        "bind-interfaces\n"
        "no-dhcp-interface=%s\n"
        "dhcp-range=%s,%s,%s\n"
        "dhcp-option=3,%s\n"
        "dhcp-option=6,%s,%s,%s\n"
        "log-dhcp\n",
        cfg->lan_iface,
        cfg->wan_iface,
        cfg->dhcp_range_start, cfg->dhcp_range_end, cfg->dhcp_lease_time,
        cfg->lan_address,
        cfg->dns_servers[0], cfg->dns_servers[1], cfg->dns_servers[2]);
    fclose(f);
    log_info("dhcp_server: wrote %s", DNSMASQ_CONF);
    return 0;
}

int dhcp_sv_start(const rd_config *cfg) {
    if (cfg == NULL) return -1;
    if (child_pid > 0) {
        log_warn("dhcp_server: already running (pid %d), stopping first", child_pid);
        dhcp_sv_stop();
    }
    if (ensure_state_dir() < 0) return -1;
    if (write_config(cfg) < 0) return -1;

    log_info("dhcp_server: starting dnsmasq");

    pid_t pid = fork();
    if (pid < 0) {
        log_error("dhcp_server: fork failed: %s", strerror(errno));
        return -1;
    }
    if (pid == 0) {
        /* -C config file, -k do NOT daemonize (we track the child). */
        execlp("dnsmasq", "dnsmasq", "-C", DNSMASQ_CONF, "-k", (char *)NULL);
        log_error("dhcp_server: execlp dnsmasq failed: %s", strerror(errno));
        _exit(127);
    }
    child_pid = pid;
    log_info("dhcp_server: dnsmasq started (pid %d)", pid);
    return 0;
}

int dhcp_sv_stop(void) {
    if (child_pid <= 0) return 0;
    log_info("dhcp_server: stopping dnsmasq (pid %d)", child_pid);
    if (kill(child_pid, SIGTERM) < 0 && errno != ESRCH) {
        log_warn("dhcp_server: SIGTERM failed (%s), trying SIGKILL", strerror(errno));
        kill(child_pid, SIGKILL);
    }
    int status;
    waitpid(child_pid, &status, 0);
    child_pid = -1;
    return 0;
}

int dhcp_sv_reload(void) {
    if (child_pid <= 0) return -1;
    log_info("dhcp_server: sending SIGHUP to dnsmasq (pid %d)", child_pid);
    if (kill(child_pid, SIGHUP) < 0) {
        log_error("dhcp_server: SIGHUP failed: %s", strerror(errno));
        return -1;
    }
    return 0;
}

bool dhcp_sv_running(void) {
    return child_pid > 0;
}
