#define _POSIX_C_SOURCE 200809L

#include "firewall.h"
#include "log.h"

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/wait.h>

/* Phase 1 firewall: nat.postrouting masquerade on WAN, filter.forward
 * accept LAN->WAN and established/related replies. Generated as a
 * single string and applied with `nft -f`. */

static const char *NFT_CONF = "/var/lib/route-daemon/nftables.conf";

static int run_cmd(const char *cmd) {
    int rc = system(cmd);
    if (rc == -1) {
        log_error("firewall: fork failed: %s", strerror(errno));
        return -1;
    }
    if (!WIFEXITED(rc) || WEXITSTATUS(rc) != 0) {
        log_error("firewall: %s failed (rc=%d)", cmd, WEXITSTATUS(rc));
        return -1;
    }
    return 0;
}

int firewall_init(void) {
    if (access("/sbin/nft", X_OK) != 0 && access("/usr/sbin/nft", X_OK) != 0) {
        log_error("firewall: nft binary not found");
        return -1;
    }
    return 0;
}

static int write_ruleset(const rd_config *cfg) {
    FILE *f = fopen(NFT_CONF, "w");
    if (f == NULL) {
        log_error("firewall: fopen %s: %s", NFT_CONF, strerror(errno));
        return -1;
    }
    fprintf(f,
        "# Generated by route-daemon\n"
        "table ip nat {\n"
        "    chain postrouting {\n"
        "        type nat hook postrouting priority srcnat;\n"
        "        oifname \"%s\" masquerade\n"
        "    }\n"
        "}\n"
        "table ip filter {\n"
        "    chain forward {\n"
        "        type filter hook forward priority 0; policy drop;\n"
        "        iifname \"%s\" oifname \"%s\" accept\n"
        "        iifname \"%s\" oifname \"%s\" ct state established,related accept\n"
        "    }\n"
        "}\n",
        cfg->wan_iface,
        cfg->lan_iface, cfg->wan_iface,
        cfg->wan_iface, cfg->lan_iface);
    fclose(f);
    log_info("firewall: wrote %s", NFT_CONF);
    return 0;
}

int firewall_apply(const rd_config *cfg) {
    if (cfg == NULL) return -1;
    if (write_ruleset(cfg) < 0) return -1;

    char cmd[512];
    snprintf(cmd, sizeof(cmd), "nft -f %s", NFT_CONF);
    if (run_cmd(cmd) < 0) return -1;

    log_info("firewall: ruleset applied (masquerade on %s)", cfg->wan_iface);
    return 0;
}

int firewall_flush(void) {
    /* Drop the tables we created. Idempotent. */
    int rc = system("nft delete table ip filter 2>/dev/null; nft delete table ip nat 2>/dev/null");
    if (rc == -1) {
        log_warn("firewall: flush fork failed");
        return -1;
    }
    log_info("firewall: flushed");
    return 0;
}
