#define _POSIX_C_SOURCE 200809L

#include "wifi_ap.h"
#include "log.h"
#include "interface.h"

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <errno.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>

// Set the LAN iface to AP mode, write hostapd.conf, and fork hostapd.

#define HOSTAPD_CONF "/var/lib/route-daemon/hostapd.conf"

static pid_t child_pid   = -1;
static bool  active      = false;
static char  ap_iface[32];

static int ensure_state_dir(void) {
    if (mkdir("/var/lib/route-daemon", 0755) < 0 && errno != EEXIST) {
        log_error("wifi_ap: mkdir: %s", strerror(errno));
        return -1;
    }
    return 0;
}

static int run_cmd(const char *cmd) {
    int rc = system(cmd);
    if (rc == -1) {
        log_error("wifi_ap: fork failed: %s", strerror(errno));
        return -1;
    }
    if (!WIFEXITED(rc) || WEXITSTATUS(rc) != 0) {
        log_error("wifi_ap: %s failed (rc=%d)", cmd, WEXITSTATUS(rc));
        return -1;
    }
    return 0;
}

static int write_hostapd_conf(const rd_config *cfg) {
    FILE *f = fopen(HOSTAPD_CONF, "w");
    if (f == NULL) {
        log_error("wifi_ap: fopen %s: %s", HOSTAPD_CONF, strerror(errno));
        return -1;
    }
    fprintf(f,
        "# Generated by route-daemon\n"
        "interface=%s\n"
        "driver=nl80211\n"
        "ssid=%s\n"
        "country_code=%s\n"
        "hw_mode=g\n"
        "channel=%d\n"
        "wpa=2\n"
        "wpa_passphrase=%s\n"
        "wpa_key_mgmt=WPA-PSK\n"
        "rsn_pairwise=CCMP\n",
        cfg->lan_iface,
        cfg->wifi_ssid,
        cfg->wifi_country,
        cfg->wifi_channel,
        cfg->wifi_password);
    fclose(f);
    log_info("wifi_ap: wrote %s (ssid=%s)", HOSTAPD_CONF, cfg->wifi_ssid);
    return 0;
}

int wifi_ap_start(const rd_config *cfg) {
    if (cfg == NULL) return -1;
    if (cfg->lan_iface[0] == '\0') {
        log_error("wifi_ap: lan_iface not set");
        return -1;
    }
    if (child_pid > 0) {
        log_warn("wifi_ap: already running, stopping first");
        wifi_ap_stop();
    }
    if (ensure_state_dir() < 0) return -1;
    if (write_hostapd_conf(cfg) < 0) return -1;

    if (iface_down(cfg->lan_iface) < 0) {
        log_warn("wifi_ap: iface_down failed (continuing)");
    }
    char cmd[300];
    snprintf(cmd, sizeof(cmd), "iw dev %s set type __ap", cfg->lan_iface);
    if (run_cmd(cmd) < 0) return -1;
    if (iface_up(cfg->lan_iface) < 0) {
        log_error("wifi_ap: iface_up after type change failed");
        return -1;
    }
    snprintf(ap_iface, sizeof(ap_iface), "%s", cfg->lan_iface);

    log_info("wifi_ap: starting hostapd");
    pid_t pid = fork();
    if (pid < 0) {
        log_error("wifi_ap: fork failed: %s", strerror(errno));
        return -1;
    }
    if (pid == 0) {
        execlp("hostapd", "hostapd", "-B", HOSTAPD_CONF, (char *)NULL);
        log_error("wifi_ap: execlp hostapd failed: %s", strerror(errno));
        _exit(127);
    }
    child_pid = pid;
    active = true;
    log_info("wifi_ap: hostapd started (pid %d)", pid);
    return 0;
}

int wifi_ap_stop(void) {
    if (child_pid <= 0) return 0;
    log_info("wifi_ap: stopping hostapd (pid %d)", child_pid);
    if (kill(child_pid, SIGTERM) < 0 && errno != ESRCH) {
        log_warn("wifi_ap: SIGTERM failed, trying SIGKILL");
        kill(child_pid, SIGKILL);
    }
    int status;
    waitpid(child_pid, &status, 0);
    child_pid = -1;
    active = false;

    if (ap_iface[0] != '\0') {
        char cmd[300];
        snprintf(cmd, sizeof(cmd), "iw dev %s set type managed", ap_iface);
        run_cmd(cmd);
    }
    return 0;
}

bool wifi_ap_running(void) {
    return child_pid > 0;
}

bool wifi_ap_active(void) {
    return active;
}
